routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::get('/profile', 'PageController@editProfile')->name('admin.profile.edit');
    Route::PUT('/profile', 'PageController@updateProfile')->name('admin.profile.update');
    // Users
    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');

    // Careers
    Route::resource('careers', 'CareerController');
    Route::get('/careers/{career}/jobs', 'CareerController@jobs')->name('careers.jobs');
    // Blogs
    Route::resource('blogs', 'BlogController');
    // Blog Sections
    Route::resource('blog/{blog}/sections', 'SectionController');
    // Services
    Route::resource('services', 'ServiceController');
    // Projects
    Route::resource('projects', 'ProjectController');
    // Testimonials
    Route::resource('testimonials', 'TestimonialController');

    Route::resource('sliders', 'SliderController');

    Route::get('projects/{project:slug}/image/{name}', 'ProjectController@deleteImage')->name('projects.delete-image');
    Route::get('projects/{project:slug}/image/{name}/form', 'ProjectController@deleteForm')->name('projects.delete-form');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create")->middleware('admin-master-user');
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store")->middleware('admin-master-user');
    Route::get('/general-settings/edit', "GeneralSettingController@edit")->name("general-settings.edit")->middleware('admin-master-user');
    Route::put('/general-settings', "GeneralSettingController@update")->name("general-settings.update")->middleware('admin-master-user');
    Route::resource('contact-enquiries', 'ContactEnquiryController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-cache', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return "<h1>Cache Cleared</h1>";
});

Auth::routes();

Route::group(["namespace" => "Frontend"], function () {
    Route::get('/', 'PageController@index')->name('pages.home');
    Route::get('/about/who-we-are', 'PageController@about')->name('pages.about');

    Route::get('/services', 'PageController@service')->name('pages.services');
    Route::get('/services/{id}', 'PageController@serviceDetail')->name('pages.service-details');
    Route::get('/service/{service:slug}', 'PageController@serviceDetails')->name('pages.service-details');


    Route::get('/blogs', 'PageController@blog')->name('pages.blogs');
    Route::get('/blog/{blog:slug}', 'PageController@blogDetails')->name('pages.blog-details');

    Route::get('/projects', 'PageController@project')->name('pages.projects');
    Route::get('/projects/{project:slug}', 'PageController@projectDetails')->name('pages.project-details');

    Route::get('/careers', 'PageController@careers')->name('pages.careers');
    Route::get('/careers/{career:slug}/job', 'PageController@careerJob')->name('pages.careers-job');
    Route::post('/careers/{career:slug}/job/apply', 'PageController@careerJobApply')->name('pages.careers-job-apply');
    Route::post('/careers/job/apply', 'PageController@careerJobTeam')->name('pages.careers-job-team');

    Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
    Route::post('/contact-enquiry', 'PageController@contactEnquiry')->name('pages.contact-enquiry');

    Route::post('/contact/form-submit', 'PageController@contactSubmit')->name('pages.contact-form-submit');

});

Route::get('/create-symlink', function () {
    $projectFolder = base_path() . '/../';
    // The file that you want to create a symlink of
    $source = $projectFolder . "/dwehidIFreyu/storage/app/public";
    // The path where you want to create the symlink of the above
    $destination = $projectFolder . "/storage";

    if (file_exists($destination)) {
        if (is_link($destination)) {
            return "<h1>Symlink already exists</h1>";
        }
    } else {
        symlink($source, $destination);
        return "<h1>Symlink created successfully</h1>";
    }
});

Route::get('/remove-symlink', function () {
    $projectFolder = base_path() . '/../';
    $destination = $projectFolder . "/storage";
    if (file_exists($destination)) {
        if (is_link($destination)) {
            unlink($destination);
            return "<h1>Removed symlink</h1>";
        }
    } else {
        return "<h1>Symlink does not exist</h1>";
    }
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Slider;
class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $sliders = Slider::latest()->get();
        return view('admin.sliders.index', compact('sliders'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.sliders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'display_order' => ['required', 'integer'],
            'image' => ['required', 'image'],
        ]);

        $image = $request->file('image');
        $filename = Str::random(15) . '.' . $image->extension();
        Storage::putFileAs("public", $image, $filename);
        $data['image'] = $filename;

        Slider::Create($data);

        return redirect()->route('sliders.index')->with('success', 'Slider created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Slider $slider)
    {
        return view('admin.sliders.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Slider $slider)
    {
        $data = $request->validate([
            'display_order' => ['required', 'integer'],
            'image' => ['nullable', 'image'],
        ]);

        if ($request->file('image')) {
            $image = $request->file('image');
            $filename = Str::random(15) . '.' . $image->extension();
            Storage::putFileAs("public", $image, $filename);
            $data['image'] = $filename;
        }

        $slider->Update($data);
        return redirect()->route('sliders.index')->with('success', 'Slider updated successfully.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slider $slider)
    {
        $slider->delete();
        return redirect()->back()->with('success', 'Slider deleted successfully.');
    }
}

resources/views/admin/sliders/create.blade.php
@extends('admin.layouts.layout')
@section('content')
@include('admin.partials.sidebar')

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Sliders</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item active">Dashboard</li>
                        <li class="breadcrumb-item active"><a href="{{ route('sliders.index') }}">Sliders</a></li>
                        <li class="breadcrumb-item active">Create</li>

                    </ul>
                </div>
            </div>
        </div>
        @include('common.partials.flash')
        <div class="row">
            <div class="col-md-12">
                <div class="card card-table">
                    <div class="card-header">
                        <h4 class="card-title">Add A New Slider</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('sliders.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row form-row">
                                <div class="col-6 col-md-6">
                                    <div class="form-group">
                                        <div class="change-avatar">
                                            <div class="upload-img">
                                                <div class="change-photo-btn">
                                                    <span class="@error('image') text-danger @enderror"><i class="fa fa-upload"></i> Upload Image <span style="color:red">*</span> </span>
                                                    <input type="file" class="@error('image') text-danger @enderror upload form-control" name="image">
                                                </div>
                                                <small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label class="@error('display_order') text-danger @enderror">Display Order <span style="color:red">*</span> </label>
                                        <input type="number" class="@error('display_order') border-danger @enderror form-control" name="display_order" value="{{ old('display_order') }}" required >
                                    </div>
                                </div>
                            </div>
                            <div class="submit-section">
                                <button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-left: 400px">
@include('admin.partials.footer')
</div>
@endsection

resources/views/admin/sliders/edit.blade.php
@extends('admin.layouts.layout')
@section('content')
@include('admin.partials.sidebar')

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Sliders</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item active">Dashboard</li>
                        <li class="breadcrumb-item active"><a href="{{ route('sliders.index') }}">Sliders</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ul>
                </div>
            </div>
        </div>
        @include('common.partials.flash')

        <div class="row">
            <div class="col-md-12">
                <div class="card card-table">
                    <div class="card-header">
                        <h4 class="card-title">Edit Slider</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('sliders.update', $slider->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row form-row">
                                <div class="col-6 col-md-6">
                                    <div class="form-group">
                                        <div class="change-avatar">
                                            <div class="profile-img" style="margin-bottom:20px;">
                                                @if($slider->image)
                                                    <img height="150" src="{{ asset('/storage/' . $slider->image) }}" alt="User image">
                                                @endif
                                            </div>
                                            <div class="upload-img">
                                                <div class="change-photo-btn">
                                                    <span class="@error('image') text-danger @enderror"><i class="fa fa-upload"></i> Upload Featured Image <span style="color:red">*</span> </span>
                                                    <input type="file" class="@error('image') text-danger @enderror upload form-control" name="image">
                                                </div>
                                                <small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-12">
                                    <div class="form-group">
                                        <label class="@error('display_order') text-danger @enderror">Display Order <span style="color:red">*</span> </label>
                                        <input type="text" class="@error('display_order') border-danger @enderror form-control" name="display_order" value="{{ old('display_order', $slider->display_order) }}" required >
                                    </div>
                                </div>
                            </div>
                            <div class="submit-section">
                                <button type="submit" class="btn btn-primary submit-btn">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="margin-left: 400px">
@include('admin.partials.footer')
</div>
@endsection

resources/views/admin/sliders/index.blade.php
@extends('admin.layouts.layout')

@section('content')
@include('admin.partials.sidebar')

<div class="page-wrapper">

    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Sliders</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item active">Dashboard</li>
                        <li class="breadcrumb-item active"><a href="{{ route('sliders.index') }}">Sliders</a></li>
                    </ul>
                </div>
            </div>
        </div>
        @include('common.partials.flash')

        <!-- /Page Header -->

        <div class="row">
            <div class="col-md-12">

                <!-- Recent Orders -->
                <div class="card card-table">
                    <div class="card-header" style="display: flex">
                        <div class="col-sm-10 col" style="margin-top:10px;">
                            <h4 class="card-title">Sliders List</h4>
                        </div>
                        <div class="col-sm-2 col">
                            <a href="{{ route('sliders.create') }}" class="btn btn-primary float-right mt-2">Add</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="datatable table table-stripped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Image</th>
                                        <th>Display Order</th>
                                        <th>Created At</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($sliders as $key => $slider)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td>
                                            <img height="80px" style="border-radius:20px" src="{{ asset('/storage/' . $slider->image) }}" />
                                        </td>
                                        <td>{{ $slider->display_order }}</td>
                                        <td>{{ $slider->created_at }}</td>
                                        <td class="text-right">
                                            <div class="actions">
                                                <a class="btn btn-sm bg-success-light" href="{{ route('sliders.edit', $slider->id) }}">
                                                    <i class="fe fe-pencil"></i> Edit
                                                </a>

                                                <a  href="#" class="btn btn-sm bg-danger-light" onclick="event.preventDefault(); if(confirm('Are you sure you want to perform this action?')){document.getElementById('delete-user-{{ $slider->id }}-form').submit();}">
                                                    <i class="fe fe-trash"></i> Delete
                                                </a>
                                                <form action="{{ route('sliders.destroy', $slider->id) }}"
                                                    id="delete-user-{{ $slider->id }}-form" method="POST"
                                                    style="display: none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="6">
                                                <div class="alert alert-info text-center">
                                                    No Sliders Added So Far
                                                    <br>
                                                    <a href="{{ route('sliders.create') }}" class="mt-2 btn btn-primary">
                                                        Add A New Sliders
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-left: 400px">
@include('admin.partials.footer')
</div>
@endsection