routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::get('/profile', 'PageController@editProfile')->name('admin.profile.edit');
    Route::PUT('/profile', 'PageController@updateProfile')->name('admin.profile.update');
    // Users
    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');

    // Careers
    Route::resource('careers', 'CareerController');
    Route::get('/careers/{career}/jobs', 'CareerController@jobs')->name('careers.jobs');
    // Blogs
    Route::resource('blogs', 'BlogController');
    // Blog Sections
    Route::resource('blog/{blog}/sections', 'SectionController');
    // Services
    Route::resource('services', 'ServiceController');
    // Projects
    Route::resource('projects', 'ProjectController');
    // Testimonials
    Route::resource('testimonials', 'TestimonialController');

    Route::resource('sliders', 'SliderController');

    Route::get('projects/{project:slug}/image/{name}', 'ProjectController@deleteImage')->name('projects.delete-image');
    Route::get('projects/{project:slug}/image/{name}/form', 'ProjectController@deleteForm')->name('projects.delete-form');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create")->middleware('admin-master-user');
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store")->middleware('admin-master-user');
    Route::get('/general-settings/edit', "GeneralSettingController@edit")->name("general-settings.edit")->middleware('admin-master-user');
    Route::put('/general-settings', "GeneralSettingController@update")->name("general-settings.update")->middleware('admin-master-user');
    Route::resource('contact-enquiries', 'ContactEnquiryController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-cache', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return "<h1>Cache Cleared</h1>";
});

Auth::routes();

Route::group(["namespace" => "Frontend"], function () {
    Route::get('/', 'PageController@index')->name('pages.home');
    Route::get('/about/who-we-are', 'PageController@about')->name('pages.about');

    Route::get('/services', 'PageController@service')->name('pages.services');
    Route::get('/services/{id}', 'PageController@serviceDetail')->name('pages.service-details');
    Route::get('/service/{service:slug}', 'PageController@serviceDetails')->name('pages.service-details');


    Route::get('/blogs', 'PageController@blog')->name('pages.blogs');
    Route::get('/blog/{blog:slug}', 'PageController@blogDetails')->name('pages.blog-details');

    Route::get('/projects', 'PageController@project')->name('pages.projects');
    Route::get('/projects/{project:slug}', 'PageController@projectDetails')->name('pages.project-details');

    Route::get('/careers', 'PageController@careers')->name('pages.careers');
    Route::get('/careers/{career:slug}/job', 'PageController@careerJob')->name('pages.careers-job');
    Route::post('/careers/{career:slug}/job/apply', 'PageController@careerJobApply')->name('pages.careers-job-apply');
    Route::post('/careers/job/apply', 'PageController@careerJobTeam')->name('pages.careers-job-team');

    Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
    Route::post('/contact-enquiry', 'PageController@contactEnquiry')->name('pages.contact-enquiry');

    Route::post('/contact/form-submit', 'PageController@contactSubmit')->name('pages.contact-form-submit');

});

Route::get('/create-symlink', function () {
    $projectFolder = base_path() . '/../';
    // The file that you want to create a symlink of
    $source = $projectFolder . "/dwehidIFreyu/storage/app/public";
    // The path where you want to create the symlink of the above
    $destination = $projectFolder . "/storage";

    if (file_exists($destination)) {
        if (is_link($destination)) {
            return "<h1>Symlink already exists</h1>";
        }
    } else {
        symlink($source, $destination);
        return "<h1>Symlink created successfully</h1>";
    }
});

Route::get('/remove-symlink', function () {
    $projectFolder = base_path() . '/../';
    $destination = $projectFolder . "/storage";
    if (file_exists($destination)) {
        if (is_link($destination)) {
            unlink($destination);
            return "<h1>Removed symlink</h1>";
        }
    } else {
        return "<h1>Symlink does not exist</h1>";
    }
});

app/ContactEnquiry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactEnquiry extends Model
{
    protected $guarded = ['g-recaptcha-response'];
}

app/Http/Controllers/Admin/ContactEnquiryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Query;

class ContactEnquiryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contactEnquiries = Query::all();
        return view('admin.contact-enquiries.index', compact('contactEnquiries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $contactEnquiry = Query::where('id', $id)->first();
        Query::destroy($contactEnquiry->id);
        $request->session()->flash('message', 'Contact Inquiry deleted successfully');
        $request->session()->flash('alert-class', 'alert alert-success');
        return redirect()->route('contact-enquiries.index');
    }
}

resources/views/admin/contact-enquiries/index.blade.php
{{-- @extends('admin.layouts.layout')

@section('heading')
    <h4>
        <a href="{{ route('admin.pages.home') }}">
            <i class="icon-arrow-left52 mr-2"></i>
        </a>
        <span class="font-weight-semibold">Home - Contact Enquiries</span> - View All
    </h4>
@endsection

@section('breadcrumbs')
    <div class="breadcrumb">
        <a href="{{ route('admin.pages.home') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item">Contact Enquiries</span>
        <span class="breadcrumb-item active">View All</span>
    </div>
@endsection

@section('content')
    @include('admin.partials.header')
    <div class="content">
        @include('common.partials.flash')
        <div class="card has-table">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">All Contact Enquiries</h5>
            </div>

            <table class="table datatable-pagination">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Comment</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($contactEnquiries as $key =>  $contactEnquiry)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $contactEnquiry->name }}</td>
                        <td>{{ $contactEnquiry->email }}</td>
                        <td>{{ $contactEnquiry->phone }}</td>
                        <td style="width:300px"> {{ $contactEnquiry->message }} </td>
                        <td class="text-center">
                            <div class="list-icons">
                                <form action="{{route('contact-enquiries.destroy',$contactEnquiry->id) }}"   method="POST">
                                    @csrf
                                    @method('Delete')
                                    <button type="submit" class=" list-icons-item text-danger-600" onclick="return confirm('Are you sure you want to delete this Contact Inquiry?')" style="background-color: Transparent; border: none;cursor:pointer;"><i class="icon-trash"></i></button>
                                </form>
                            </div>
                        </td>
                        <td style="display: none"></td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6">
                            <div class="alert alert-info text-center">
                                No Contact Enquiries So Far
                            </div>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
<div style="margin-left: 400px">
@include('admin.partials.footer')
</div>  @endsection

@push('scripts')
    <script src="{{asset('backend/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script src="{{asset('backend/js/demo_pages/datatables_basic.js')}}"></script>
@endpush --}}

@extends('admin.layouts.layout')

@section('content')
@include('admin.partials.sidebar')

<div class="page-wrapper">

    <div class="content container-fluid">

        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Projects</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item active">Dashboard</li>
                        <li class="breadcrumb-item active"><a href="{{ route('projects.index') }}">Projects</a></li>
                    </ul>
                </div>
            </div>
        </div>
        @include('common.partials.flash')

        <!-- /Page Header -->

        <div class="row">
            <div class="col-md-12">

                <!-- Recent Orders -->
                <div class="card card-table">
                    <div class="card-header" style="display: flex">
                        <div class="col-sm-10 col" style="margin-top:10px;">
                            <h4 class="card-title">Projects List</h4>
                        </div>
                        <div class="col-sm-2 col">
                            <a href="{{ route('projects.create') }}" class="btn btn-primary float-right mt-2">Add</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="datatable table table-stripped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Comment</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($contactEnquiries as $key => $contactEnquiry)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $contactEnquiry->name }}</td>
                                        <td>{{ $contactEnquiry->email }}</td>
                                        <td>{{ $contactEnquiry->phone }}</td>
                                        <td style="width:300px"> {{ $contactEnquiry->message }} </td>
                                        <td class="text-center">
                                            <div class="list-icons">
                                                <form action="{{route('contact-enquiries.destroy',$contactEnquiry->id) }}"   method="POST">
                                                    @csrf
                                                    @method('Delete')
                                                    <button type="submit" class=" list-icons-item text-danger-600" onclick="return confirm('Are you sure you want to delete this Contact Inquiry?')" style="background-color: Transparent; border: none;cursor:pointer;"><i class="fe fe-trash"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="6">
                                                <div class="alert alert-info text-center">
                                                    No Projects Added So Far
                                                    <br>
                                                    <a href="{{ route('projects.create') }}" class="mt-2 btn btn-primary">
                                                        Add A New Project
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="margin-left: 400px">
@include('admin.partials.footer')
</div>
@endsection
@push('script')
    <script>
        $('.activeInactive').change(function(status){
            var user_id = this.getAttribute('data-status-id');
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: 'get',
                url: "/admin/"+ user_id +"/set-status/"+status.target.value,
                dataType: 'json',
                success:function(data){
                    if(data == 'done')
                    {
                        $('#status').bootstrapToggle('on');
                    }
                }
            });
        });
    </script>
@endpush