routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['prefix' => 'admin', "middleware" => "auth:admin", "namespace" => "AdminAuth", "as" => "admin."], function () {
    Route::get('/change-password', 'ChangePasswordController@changePassword')->name('change-password.edit');
    Route::put('/change-password', 'ChangePasswordController@updatePassword')->name('change-password.update');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin', "namespace" => "Admin"], function () {
    Route::get('/', 'PageController@index')->name('admin.pages.home');
    Route::get('/profile', 'PageController@editProfile')->name('admin.profile.edit');
    Route::PUT('/profile', 'PageController@updateProfile')->name('admin.profile.update');
    // Users
    Route::resource('users', 'UserController');
    Route::get('/{id}/set-status/{status}', 'UserController@setStatus')->name('admin.user-status');
    Route::get('/user/{user}/change-password', 'UserController@changePassword')->name('admin.users.change-password');
    Route::put('/user/{user}/update-password', 'UserController@updatePassword')->name('admin.users.update-password');

    // Careers
    Route::resource('careers', 'CareerController');
    Route::get('/careers/{career}/jobs', 'CareerController@jobs')->name('careers.jobs');
    // Blogs
    Route::resource('blogs', 'BlogController');
    // Blog Sections
    Route::resource('blog/{blog}/sections', 'SectionController');
    // Services
    Route::resource('services', 'ServiceController');
    // Projects
    Route::resource('projects', 'ProjectController');
    // Testimonials
    Route::resource('testimonials', 'TestimonialController');

    Route::resource('sliders', 'SliderController');

    Route::get('projects/{project:slug}/image/{name}', 'ProjectController@deleteImage')->name('projects.delete-image');
    Route::get('projects/{project:slug}/image/{name}/form', 'ProjectController@deleteForm')->name('projects.delete-form');
    // Contact Inquiries
    Route::get('/general-settings/create', "GeneralSettingController@create")->name("general-settings.create")->middleware('admin-master-user');
    Route::post('/general-settings', "GeneralSettingController@store")->name("general-settings.store")->middleware('admin-master-user');
    Route::get('/general-settings/edit', "GeneralSettingController@edit")->name("general-settings.edit")->middleware('admin-master-user');
    Route::put('/general-settings', "GeneralSettingController@update")->name("general-settings.update")->middleware('admin-master-user');
    Route::resource('contact-enquiries', 'ContactEnquiryController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-cache', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    return "<h1>Cache Cleared</h1>";
});

Auth::routes();

Route::group(["namespace" => "Frontend"], function () {
    Route::get('/', 'PageController@index')->name('pages.home');
    Route::get('/about/who-we-are', 'PageController@about')->name('pages.about');

    Route::get('/services', 'PageController@service')->name('pages.services');
    Route::get('/services/{id}', 'PageController@serviceDetail')->name('pages.service-details');
    Route::get('/service/{service:slug}', 'PageController@serviceDetails')->name('pages.service-details');


    Route::get('/blogs', 'PageController@blog')->name('pages.blogs');
    Route::get('/blog/{blog:slug}', 'PageController@blogDetails')->name('pages.blog-details');

    Route::get('/projects', 'PageController@project')->name('pages.projects');
    Route::get('/projects/{project:slug}', 'PageController@projectDetails')->name('pages.project-details');

    Route::get('/careers', 'PageController@careers')->name('pages.careers');
    Route::get('/careers/{career:slug}/job', 'PageController@careerJob')->name('pages.careers-job');
    Route::post('/careers/{career:slug}/job/apply', 'PageController@careerJobApply')->name('pages.careers-job-apply');
    Route::post('/careers/job/apply', 'PageController@careerJobTeam')->name('pages.careers-job-team');

    Route::get('/contact-us', 'PageController@contactUs')->name('pages.contact-us');
    Route::post('/contact-enquiry', 'PageController@contactEnquiry')->name('pages.contact-enquiry');

    Route::post('/contact/form-submit', 'PageController@contactSubmit')->name('pages.contact-form-submit');

});

Route::get('/create-symlink', function () {
    $projectFolder = base_path() . '/../';
    // The file that you want to create a symlink of
    $source = $projectFolder . "/dwehidIFreyu/storage/app/public";
    // The path where you want to create the symlink of the above
    $destination = $projectFolder . "/storage";

    if (file_exists($destination)) {
        if (is_link($destination)) {
            return "<h1>Symlink already exists</h1>";
        }
    } else {
        symlink($source, $destination);
        return "<h1>Symlink created successfully</h1>";
    }
});

Route::get('/remove-symlink', function () {
    $projectFolder = base_path() . '/../';
    $destination = $projectFolder . "/storage";
    if (file_exists($destination)) {
        if (is_link($destination)) {
            unlink($destination);
            return "<h1>Removed symlink</h1>";
        }
    } else {
        return "<h1>Symlink does not exist</h1>";
    }
});

resources/views/admin/partials/footer.blade.php
<!-- Footer -->
<footer class="footer">
    <!-- Footer Bottom -->
    <div class="footer-bottom">
        <div class="container-fluid">
            <!-- Copyright -->
            <div class="copyright">
                <div class="row">
                    <div class="col-xl-12 col-sm-12 col-12" style="padding:1.875rem 1.875rem 0;">
                        <div class="card">
                            <div class="card-body">
                                <h6 style="text-align: right">Copyrights 2021 ©️ <b>Orion</b>. All Rights Reserved.
                                    Powered by <b>DEVEOLOGY</b></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Copyright -->
    </div>
    </div>
    <!-- /Footer Bottom -->
</footer>

resources/views/admin/partials/header.blade.php
<div class="header">

    <!-- Logo -->
    <div class="header-left">
        <a href="{{ route('admin.pages.home') }}" class="logo">
            <img src="{{ asset('images/logo/logo.png') }}" alt="Logo">
        </a>
        <a href="{{ route('admin.pages.home') }}" class="logo logo-small">
            <img src="{{ asset('images/golder.png') }}" alt="Logo" width="30" height="30">
        </a>
    </div>
    <!-- /Logo -->

    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fe fe-text-align-left"></i>
    </a>

    {{-- <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div> --}}

    <!-- Mobile Menu Toggle -->
    <a class="mobile_btn" id="mobile_btn">
        <i class="fa fa-bars"></i>
    </a>
    <!-- /Mobile Menu Toggle -->

    <!-- Header Right Menu -->
    <ul class="nav user-menu">
        <!-- User Menu -->
        @if(Auth::guard('admin')->check())
            @auth
                <li class="nav-item dropdown noti-dropdown">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="fe fe-bell"></i> <span class="badge badge-pill">3</span>
                    </a>
                    <div class="dropdown-menu notifications">
                        <div class="topnav-dropdown-header">
                            <span class="notification-title">Notifications</span>
                        </div>
                        <div class="noti-content">
                            <ul class="notification-list">
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown has-arrow">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <span class="user-img"><img style="margin-right:10px;" class="rounded-circle" style="margin-right:10px" @isset($settings)
                            src="{{ asset('/storage/' . $settings->site_logo) }}"
                        @else
                            src="{{ asset('images/logo/logo.png') }}"
                        @endisset
                        width="50" height="45" alt="Ryan Taylor">
                            {{ Auth::user()->username }}
                        </span>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ route('admin.profile.edit') }}">My Profile</a>
                        <a href="{{ route('admin.logout') }}" class="dropdown-item"
                            onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                            <i class="icon-switch2"></i>
                            Logout
                        </a>
                        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                        @csrf
                       </form>
                    </div>
                </li>
            @endauth
        @else
            <li class="nav-item">
                <a class="nav-link header-login"  href="{{route('admin.login')}}">login / Signup </a>
            </li>
        @endif
        <!-- /User Menu -->
    </ul>
    <!-- /Header Right Menu -->
</div>

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title">
                    <span>Main</span>
                </li>
                <li>
                    <a class="{{ (request()->routeIs('admin.pages.home')) ? 'active' : '' }}" href="{{ route('admin.pages.home') }}">
                        <i class="fe fe-home"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="submenu" >
                    <a href="#" class="{{ (request()->routeIs('projects.*')) ? 'active' : '' }}" >
                        <i class="fas fa-project-diagram" style='font-size:19px'></i>
                        <span>Projects</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul style="display: none;">
                        <li><a class="{{ (request()->routeIs('projects.create')) ? 'active' : '' }}" href="{{ route('projects.create') }}">Add A New Project</a></li>
                        <li><a class="{{ (request()->routeIs('projects.index')) ? 'active' : '' }}" href="{{ route('projects.index') }}">View All Projects</a></li>
                    </ul>
                </li>
                <li class="submenu" >
                    <a href="#" class="{{ (request()->routeIs('careers.*')) ? 'active' : '' }}" >
                        <i class="fas fa-project-diagram" style='font-size:19px'></i>
                        <span>Careers</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul style="display: none;">
                        <li><a class="{{ (request()->routeIs('careers.create')) ? 'active' : '' }}" href="{{ route('careers.create') }}">Add A New Career</a></li>
                        <li><a class="{{ (request()->routeIs('careers.index')) ? 'active' : '' }}" href="{{ route('careers.index') }}">View All Careers</a></li>
                    </ul>
                </li>
                <li class="submenu" >
                    <a href="#" class="{{ (request()->routeIs('blogs.*')) ? 'active' : '' }} {{ (request()->routeIs('sections.*')) ? 'active' : '' }}" >
                        <i class="fas fa-project-diagram" style='font-size:19px'></i>
                        <span>Blogs</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul style="display: none;">
                        <li><a class="{{ (request()->routeIs('blogs.create')) ? 'active' : '' }}" href="{{ route('blogs.create') }}">Add A New Blog</a></li>
                        <li><a class="{{ (request()->routeIs('blogs.index')) ? 'active' : '' }}" href="{{ route('blogs.index') }}">View All Blogs</a></li>
                    </ul>
                </li>
                <li class="submenu" >
                    <a href="#" class="{{ (request()->routeIs('services.*')) ? 'active' : '' }} {{ (request()->routeIs('sections.*')) ? 'active' : '' }}" >
                        <i class="fas fa-project-diagram" style='font-size:19px'></i>
                        <span>Services</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul style="display: none;">
                        <li><a class="{{ (request()->routeIs('services.create')) ? 'active' : '' }}" href="{{ route('services.create') }}">Add A New Service</a></li>
                        <li><a class="{{ (request()->routeIs('services.index')) ? 'active' : '' }}" href="{{ route('services.index') }}">View All Services</a></li>
                    </ul>
                </li>
                <li class="submenu" >
                    <a href="#" class="{{ (request()->routeIs('testimonials.*')) ? 'active' : '' }}" >
                        <i class="fas fa-project-diagram" style='font-size:19px'></i>
                        <span>Testimonials</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul style="display: none;">
                        <li><a class="{{ (request()->routeIs('testimonials.create')) ? 'active' : '' }}" href="{{ route('testimonials.create') }}">Add A New Testimonial</a></li>
                        <li><a class="{{ (request()->routeIs('testimonials.index')) ? 'active' : '' }}" href="{{ route('testimonials.index') }}">View All Testimonials</a></li>
                    </ul>
                </li>
                <li>
                    <a class="{{ (request()->routeIs('contact-enquiries.*')) ? 'active' : '' }}" href="{{ route('contact-enquiries.index') }}">
                        <i class="fe fe-envelop"></i>
                        <span>Contact Enquiries</span>
                    </a>
                </li>
                <li>
                    <a class="{{ (request()->routeIs('admin.change-password.*')) ? 'active' : '' }}" href="{{ route('admin.change-password.edit') }}">
                        <i class="fe fe-lock"></i>
                        <span>Change Password</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('admin-logout').submit();">
                        <i class="fe fe-lock"></i>
                        <span>Logout</span>
                    </a>
                </li>
            </ul>
            <form id="admin-logout" action="{{ route('admin.logout') }}" method = "POST" style="display: none;">@csrf</form>
        </div>
    </div>
</div>